# Generated by Django 3.2.3 on 2021-06-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_rename_bikes_bike'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('hours', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
