# Generated by Django 3.2.3 on 2021-06-08 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rent', '0003_rent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='enddate',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='startdate',
        ),
        migrations.AddField(
            model_name='rent',
            name='bike',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rent.bike'),
        ),
        migrations.AddField(
            model_name='rent',
            name='endtime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='starttime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='uname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rent',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='hours',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
