# Generated by Django 3.2.3 on 2021-06-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0005_auto_20210612_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
