# Generated by Django 3.2.3 on 2021-06-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0006_alter_rent_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
