# Generated by Django 3.2.3 on 2021-06-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0007_rent_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='hours',
            field=models.FloatField(null=True),
        ),
    ]
